DROP DATABASE IF EXISTS BET365;

CREATE DATABASE BET365;

USE BET365;

CREATE TABLE Jugadores(
ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nombre TEXT,
Edad INTEGER,
Victorias INTEGER
);


CREATE TABLE Contrasenas(
ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Contrasena TEXT NOT NULL,
FOREIGN KEY (ID) REFERENCES Jugadores(Id)
);


CREATE TABLE Partidas(
Id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
Resultado TEXT,
Fecha TEXT
);
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Raul','10102000');
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Dennis','14102020');
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Raul','01010001');
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Dennis','01010001');
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Marian','01010001');
INSERT INTO Partidas(Resultado,Fecha) VALUES ('Raul','01010001');
